---
- name: create group
  group: 
     name: tomcat 
     state: present

- name: create user
  user:
     name: tomcat
     group: tomcat
     shell: /bin/false
     home: /opt/tomcat   
     state: present  