---
- name: manage web 
  template: 
     src: templates/manage.j2
     dest: /opt/tomcat/conf/tomcat-users.xml

- name: manager
  template: 
     src: templates/manager.j2  
     dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: host-manager
  template:
     src: templates/hostmanager.j2
     dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml    