---
- name: group permission 
  file:
     group: tomcat
     recurse: yes
     path: /opt/tomcat
     state: directory 

- name: group read access
  file:
     path: /opt/tomcat/conf
     recurse: yes
     mode: g+r
     state: directory

- name: group readaccess2
  file: 
     path: /opt/tomcat/conf      
     mode: g+x
     state: directory

- name: owner permission
  file:
     owner: tomcat
     recurse: yes
     path: /opt/tomcat/webapps/
     state: directory

- name: owner permission
  file:
     owner: tomcat
     recurse: yes
     path: /opt/tomcat/work/
     state: directory

- name: owner permission
  file:
     owner: tomcat
     recurse: yes
     path: /opt/tomcat/temp/
     state: directory

- name: owner permission
  file:
     owner: tomcat
     recurse: yes
     path: /opt/tomcat/logs/     
     state: directory







          