---
- hosts: 172.31.30.63
  become: yes
  tasks: 
  - name: install webserver
    apt:
      name: apache2
      state: present
    notify: restartwebserver

  - name: edit webpage
    template:    
      src: myidenx.j2 
      dest: /var/www/html/index.html 
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
  
