---
- hosts: mywebservers
  become: yes
  tasks:
  - name:
    apt:
      name: "{{myjavainstaller}}"
      state: present
      when: ansible_os_family == "Debian"
  - name:
    yum:
      name: "{{myjavainstaller2}}"
      state: started
      when: ansible_os_family == "RedHat"       