---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on ansible ubuntu nodes
    apt:
      name: "{{mywebserverubuntu}}"
      state: present
    when: ansible_os_family == "Debian"  
  
  - name: i want to start webserver on ansible ubuntu nodes
    service:
        name: "{{mywebserverubuntu}}"
        state: started
    when: ansible_os_family == "Debian"    

  - name: i want to install webserver on ansible RedHat nodes
    yum:
      name: "{{mywebserevrRedHat}}"
      state: present
    when: ansible_os_family == "RedHat"  

  - name: i want start webserver on ansible RedHat nodes
    service:
        name: "{{mywebserevrRedHat}}"
        state: started
    when: ansible_os_family == "RedHat"    

   