---
- hosts: 172.31.42.135
  become: yes
  vars:
    var1: git 
    var2: tree
    var3: wget
  tasks:
  - name: display tree
    debug: 
      msg: "{{var1}}"  
  - name: install git
    yum:
      name: "{{item}}"    
      state: present
    loop:
       - "{{var1}}"  
       - "{{var2}}"
       - "{{var3}}"
  - name: display loop   
    debug:
      msg: "{{yum}}"   