---
- hosts: 172.31.30.63
  become: yes
  vars:
    myvar1: git 
    myvar2: wget
    myvar3: tree
  tasks:
  - name: i want to display git
    debug:
      msg: "{{myvar3}}"  

  - name: i want to install git ubuntu nodes
    apt:
      name: "{{item}}"    
      state: present
    loop: 
       - "{{myvar3}}"  
       - "{{myvar2}}"
       - "{{myvar1}}"