--- 
- hosts: webservers2
  become: yes
  vars: 
    var1: "{{installgit}}"
    var2: "{{installwget}}"
  tasks: 
  - name: install git in ubuntu
    apt:
      name: "{{item}}"  
      state: present
    when: ansible_os_family == "Debian"
    loop: 
       - "{{var1}}"
       - "{{var2}}"
  - name: install wget in RedHat
    yum:
      name: "{{item}}"   
      state: present
    when: ansible_os_family == "RedHat"
    loop: 
       - "{{var1}}"
       - "{{var2}}"

         