---
- hosts: 172.31.30.63
  become: yes
  tasks: 
  - name: install tree
    apt:
      name: tree
      staaate: present
    tags: mytree
    ignore_errors: True

  - name: install git
    apt: 
      name: git
      state: present
    tags: mygit
  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget
