---
- name: tomcat group
  group:
    name: tomcat
    state: present

- name: tomcat user
  user:
    name: tomcat
    shell: /bin/false
    home: /opt/tomcat
    group: tomcat     
    state: present