---
# tasks file for Role1


- name: install webservers
  apt: 
    name: apache2
    state: present
  notify: restartwebserver

- name: edit text in webpage
  template:
    src: index.j2
    dest: /var/www/html/index.html
  notify: restartwebserver      