---
- name: group ownership
  file:
     group: tomcat 
     path: /opt/tomcat
     recurse: yes 
     state: directory

- name: groupaccess
  file:
     path: /opt/tomcat/conf
     mode: g+r
     recurse: yes
     state: directory

- name: groupaccess2
  file:
     path: /opt/tomcat/conf  
     mode: g+x
     state: directory

- name: ownership
  file: 
     path: /opt/tomcat/webapps/
     recurse: yes
     owner: tomcat
     state: directory

- name: ownership
  file: 
     path: /opt/tomcat/work/
     recurse: yes
     owner: tomcat
     state: directory     

- name: ownership
  file: 
     path: /opt/tomcat/temp/
     recurse: yes
     owner: tomcat
     state: directory     

- name: ownership
  file: 
     path: /opt/tomcat/logs/
     recurse: yes
     owner: tomcat
     state: directory                  
